[package]
name = "rustere"
version = "0.2.0"
description = "Rust template repository"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
